services:
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - ./redis:/data
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_HOST=${REDIS_HOST}
        command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
        restart: unless-stopped
