import "@/styles/globals.css"

import { GeistSans } from "geist/font/sans"
import { type Metadata } from "next"

import { TRPCReactProvider } from "@/trpc/react"
import { ThemeProvider } from "@/components/ThemeProvider"
import Navbar from "@/components/Header/Nav/Navbar"

export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" className={`${GeistSans.variable}`}>
            <body className="bg-slate-950">
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem
                    disableTransitionOnChange
                >
                    <TRPCReactProvider>
                        <div className="flex">
                            <Navbar />
                            <div
                                className="relative flex-grow"
                                style={{ maxWidth: "calc(100vw - 80px)" }}
                            >
                                {children}
                            </div>
                        </div>
                    </TRPCReactProvider>
                </ThemeProvider>
            </body>
        </html>
    )
}

