import "@/styles/globals.css"

import { GeistSans } from "geist/font/sans"
import { type Metadata } from "next"

import { TRPCReactProvider } from "@/trpc/react"
import { ThemeProvider } from "@/components/ThemeProvider"
import Navbar from "@/components/Header/Nav/Navbar"
import { SpotifyProvider } from "@/lib/Context/SpotifyContext"
import Footer from "@/components/Footer/Footer"
import { QueueProvider } from "@/lib/Context/QueueContext"

export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" className={`${GeistSans.variable}`}>
            <body className="overflow-x-hidden bg-slate-950 antialiased">
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem
                    disableTransitionOnChange
                >
                    <TRPCReactProvider>
                        <SpotifyProvider>
                            <QueueProvider>
                                <div className="flex">
                                    <Navbar />
                                    <main
                                        className="relative flex-grow"
                                        style={{
                                            maxWidth: "calc(100vw - 80px)",
                                        }}
                                    >
                                        {children}
                                        <Footer />
                                    </main>
                                </div>
                            </QueueProvider>
                        </SpotifyProvider>
                    </TRPCReactProvider>
                </ThemeProvider>
            </body>
        </html>
    )
}

